### ISSUE TITLE
Processor handling of signs other than 0 or 1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pkimpel/retro-205#4]
```
It is not clear that the processor is always handling signs properly when they 
have a value other than zero or one, especially in the arithmetic operators. 
Several problems were fixed with Extract (63) and the Clear and XXX (64-67) in 
0.03e (r35), but it is not entirely clear how the higher order bits of sign 
digits should be handled for the integer Add/Subtract operators. At present 
these operators set all the higher-order bits of the sign to zero.
```

Original issue reported on code.google.com by `paul.kimpel@digm.com` on 23 Feb 2015 at 4:40

**Comment by pkimpel** [comment]
Resolved in release 0.05. D205Processor.integerAdd() was checking the entire sign digit to determine positive/negative instead of just the low-order bit of the sign digit.

The checksum routine in Tom Sawyer's transcription of the Burroughs Algebraic Compiler tape now successfully computes the checksum when loading the tape.
